### ISSUE TITLE
'NoneType' object has no attribute 'enum_types_by_name'

### ISSUE THREAD

**Issue by qazwsdc** [YunzhiYike/kuaishou-live#1]
Traceback (most recent call last):
  File "C:\Users\XY\Downloads\kuaishou-live-main\main.py", line 4, in <module>
    from kuaishou import KsLive
  File "C:\Users\XY\Downloads\kuaishou-live-main\kuaishou\KsLive.py", line 13, in <module>
    from .ks_pb2 import CSWebEnterRoom
  File "C:\Users\XY\Downloads\kuaishou-live-main\kuaishou\ks_pb2.py", line 20, in <module>
    _COMPRESSIONTYPE = DESCRIPTOR.enum_types_by_name['CompressionType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

**Comment by qazwsdc** [comment]
已解决。重新编译proto即可

**Comment by YunzhiYike** [comment]
好的👌

**Comment by qazwsdc** [comment]
多次测试发现在请求一定次数的streamid后，会请求不到。手动将streamid改写后又能跑起来
所以获取streamid似乎是个玄学。尝试了各种请求头和参数，似乎都无法很好解决，但浏览器去访问却又能访问到……

**Comment by YunzhiYike** [comment]
可以直接改写获取房间号ID的那个方法，原始的是想直接用正则直接匹配出json文本，顺带把用户的信息也提取出来，如果房间号在批量操作的时候存在问题时候可以考虑更换代理IP或者可以自己写一个方法直接用正则匹配文本呢？

**Comment by qazwsdc** [comment]
不是的，你没理解意思。现象是requests请求到的返回值里面根本找不到房间号，但你用浏览器去访问又能请求到……

**Comment by YunzhiYike** [comment]
你是对同一个直播地址做多次获取房间号吗？

**Comment by YunzhiYike** [comment]
刚刚尝试了一下，出现获取不了的时候浏览器也不行，再次刷新浏览器的直播就没了，这个可以通过更换代理IP来解决

**Comment by YunzhiYike** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/108213897/204096492-368a1164-6aa8-4536-9558-57c9daf222a9.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/108213897/204096527-dfc35d9f-9d9d-45a3-a8a2-e408f4d90b3e.png">

**Comment by qazwsdc** [comment]
你这个明显是ip问题，但我碰到的情况就是，脚本获取不到房间号，浏览器却可以
另外我是登录状态

**Comment by YunzhiYike** [comment]
做一点延时试试

**Comment by YunzhiYike** [comment]
做一点延时试试

**Comment by YunzhiYike** [comment]
做一点延时试试

**Comment by qazwsdc** [comment]
感觉很玄学啊。先不说我的情况，你会不会碰到ip被封？而且是在登录的状态？如果很容易就不能用的话那不是要频繁换ip么

**Comment by YunzhiYike** [comment]
我也是登录状态，一个IP频繁访问会触发风控大概要等1分钟左右

**Comment by qazwsdc** [comment]
你说的频繁访问是指的同时访问不同直播间么？
如果我只是访问单个直播间应该没事吧

**Comment by YunzhiYike** [comment]
不管是一个还是多个，只要是批量的方式访问都会存在的

**Comment by qazwsdc** [comment]
你这个脚本不存在批量访问吧，只是开启一个直播间，一个ws连接，应该没事吧

**Comment by YunzhiYike** [comment]
单个直播间，在启动websocket客户端的时候会取一次房间号，如果是这样的话就不会触发风控

**Comment by qazwsdc** [comment]
还有个问题。。比方说我在公司 的电脑上可以正常访问直播，把这个cookie复制到家里，再请求就会请求不到。这cookie是绑定ip了吗

**Comment by YunzhiYike** [comment]
是的，开启一个直播间就是一个ws连接，风控一个是在做http操作的时候才会触发，ws不会处罚风控

**Comment by qazwsdc** [comment]
ws不触发风控说不通啊，因为我把公司的cookie，复制到家里，请求不到ws链接

**Comment by YunzhiYike** [comment]
ws地址是通过快手http的API接口获取的，应该是刚刚上述说的http方面的风控

**Comment by qazwsdc** [comment]
那我是不是可以在没有风控的ip去获取到ws地址，然后到有风控的ip正常连接到ws

**Comment by YunzhiYike** [comment]
是的

**Comment by qazwsdc** [comment]
行，我再试试，谢谢老哥

**Comment by qazwsdc** [comment]
对了你不是说风控要等一分钟？为什么家里的ip，好几天了还是获取不到ws地址

**Comment by YunzhiYike** [comment]
我刚刚试了一个账户在不同地方登录再提取出cookie回到我自己这边的电脑进行测试，也是没有问题的，所以你在公司登录的账户提取出来的cookie可以直接放到自己电脑上跑脚本

**Comment by YunzhiYike** [comment]
> 对了你不是说风控要等一分钟？为什么家里的ip，好几天了还是获取不到ws地址

这个需要看一下日志信息，你看一下日志。

**Comment by qazwsdc** [comment]
问题是家里的ip一直是获取不到ws地址，复制了公司的cookie也不行，浏览器打开表现为能看直播画面，右边看不到任何弹幕信息

**Comment by YunzhiYike** [comment]
> 对了你不是说风控要等一分钟？为什么家里的ip，好几天了还是获取不到ws地址

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/108213897/204099458-df8929a0-2032-4305-8bb3-15ba3201d58d.png">

**Comment by qazwsdc** [comment]
我擦我按了一下f12，打开chrome调试窗口，竟然发现浏览器里面正常了，ws地址也有了，这是什么情况啊，我没换ip啊

**Comment by YunzhiYike** [comment]
> 我擦我按了一下f12，打开chrome调试窗口，竟然发现浏览器里面正常了，ws地址也有了，这是什么情况啊，我没换ip啊

是不是电脑问题？重启一下或者换电脑测试一下这种情况，我是Mac，没有遇到你说的这个问题

**Comment by qazwsdc** [comment]
可能是浏览器缓存问题……我再试试吧

**Comment by YunzhiYike** [comment]
> 可能是浏览器缓存问题……我再试试吧

好的👌

**Comment by qazwsdc** [comment]
谢谢老哥了

**Comment by YunzhiYike** [comment]
> 谢谢老哥了

没事

**Comment by YunzhiYike** [comment]
> Traceback (most recent call last): File "C:\Users\XY\Downloads\kuaishou-live-main\main.py", line 4, in from kuaishou import KsLive File "C:\Users\XY\Downloads\kuaishou-live-main\kuaishou\KsLive.py", line 13, in from .ks_pb2 import CSWebEnterRoom File "C:\Users\XY\Downloads\kuaishou-live-main\kuaishou\ks_pb2.py", line 20, in _COMPRESSIONTYPE = DESCRIPTOR.enum_types_by_name['CompressionType'] AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
