### ISSUE TITLE
貌似接口获取不到信息了 WebSocketInfoQuery  返回是空的了，官方关闭了这个接口？

### ISSUE THREAD

**Issue by wgscd** [YunzhiYike/kuaishou-live#2]
貌似接口获取不到信息了 WebSocketInfoQuery  返回是空的了，官方关闭了这个接口？

**Comment by YunzhiYike** [comment]
> ### **[wgscd](/wgscd) ** commented [Dec 10, 2022](#issue-1488522885)

已经修复

**Comment by YunzhiYike** [comment]
> 貌似接口获取不到信息了 WebSocketInfoQuery 返回是空的了，官方关闭了这个接口？
