### ISSUE TITLE
liveGraphql返回404

### ISSUE THREAD

**Issue by ALiaoSha** [YunzhiYike/kuaishou-live#4]
执行到liveGraphql 方法的时候报404该怎么解决？ 是ks封了这个接口吗？   
[liveGraphql] [操作返回数据] ｜ {"result": 1026, "error_msg": "[1026] 404 NOT FOUND", "request_id": "673169315571464600"}

**Comment by YunzhiYike** [comment]
> 执行到liveGraphql 方法的时候报404该怎么解决？ 是ks封了这个接口吗？ [liveGraphql] [操作返回数据] ｜ {"result": 1026, "error_msg": "[1026] 404 NOT FOUND", "request_id": "673169315571464600"}

已经修复
